### ISSUE TITLE
[FP]: Duplicate array keys

### ISSUE THREAD

**Issue by voku** [kalessil/phpinspectionsea#1272]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 2.0.14  |
| Language level | PHP 7.0                         |

Current behaviour
--
"Duplicate array keys" is shown for this code

```php
<?php

define('ICON_BUTTON_BRIEFCASE', 'lall-font-fallback/PNG/briefcase.png');
define('ICON_BUTTON_BULLHORN', 'lall-font-fallback/PNG/bullhorn.png');
define('ICON_BUTTON_BUILDING', 'lall-font-fallback/PNG/building.png');

$arrayTmp = [
    ICON_BUTTON_BRIEFCASE => 'foo',
    ICON_BUTTON_BULLHORN  => 'bar',
    ICON_BUTTON_BUILDING  => 'lall',
];

var_dump($arrayTmp);
```

Expected behaviour
--
no error about duplicate array keys

Environment details
---
PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-142-generic

**Comment by orklah** [comment]
Hi, this is a PhpStorm native inspection
PHP > Probable bugs > Duplicate array keys

This is a change that has been made in PhpStorm since a few months (maybe in 2019.1 EAP, I don't remember) for performance reason, only the 24 first characters of the variable are used in the comparison. You can find a related YouTrack issue here:
https://youtrack.jetbrains.com/issue/WI-46077

**Comment by voku** [comment]
@orklah Thanks for feedback, we will see if PhpStorm will fix it 😄
