### ISSUE TITLE
[FR] suggest elvis operator and null coalesce operator instead of conditionnal execution

### ISSUE THREAD

**Issue by orklah** [kalessil/phpinspectionsea#1442]
Description:
--
The elvis operator(?:) and null coalesce operator (??) allow us to replace that kind of syntax:
```php
$a === null && $a = 'value';
//replaced by
$a = $a ?? 'value'; // bonus: no more notice if $a wasn't set

!isset($a) && $a = 'value';
//replaced by
$a = $a ?? 'value';

$a == false && $a = 'value';
//replaced by
$a = (!$a ?: 'value');

$a == true && $a = 'value';
//replaced by
$a = ($a ?: 'value');

func($a) && $a = 'value';
//replaced by
$a = (func($a) ?: 'value');

// All the previous syntax are only valid in assignment context. If there is a reading of the return value , the result is not guaranteed. For example:
$b = ($a === null && $a = 'value');
//$b will be either false (if $a !== null) or true
$b = ($a = $a ?? 'value');
//$b will be either null or 'value'

```

The parenthesis are optionnal, but I think they improve readability.

Thanks

**Comment by kalessil** [comment]
Thank you for proposal @orklah, I evaluated cases on multiple OSS projects and noticed behaviour changes when doing some of replacements (because of PHP or because of OSS project magic).

As of project history, behaviour changes are negatively accepted by community, so I have to decline this ticket.

I recently declining tickets, hope this is not hurting you emotionally and I want to say that I'm super thankfull to your constant feedback - it made Extended so much better. Please continue!

**Comment by orklah** [comment]
Thanks for looking at the issue! Don't worry, I know you can't accept all features, feel free to close them if it's too much work or if it doesn't fit the philosophy of the project!
