### ISSUE TITLE
PHPStorm wrong detects new returned type

### ISSUE THREAD

**Issue by xepozz** [kalessil/phpinspectionsea#1598]
![image](https://user-images.githubusercontent.com/6815714/86958240-8629d400-c164-11ea-932b-7e4bc2465d14.png)
![image](https://user-images.githubusercontent.com/6815714/86958251-888c2e00-c164-11ea-9138-17e83033d122.png)
![image](https://user-images.githubusercontent.com/6815714/86958259-8a55f180-c164-11ea-9721-fb5a5849670f.png)

The inspections should say that returned type of `withUri` is `ServerRequestInterface` instead of `RequestInterface`
P.S. Interfaces in https://github.com/php-fig/log

**Comment by kalessil** [comment]
Thank you for reporting @xepozz, I took a deep look into the issue and it appears to be caused by how IDE infers 'static' return type. It should resolve it as a child interface, but it doesn't.

In older IDEversion the raw 'static' was returned and we handling it, but currently, we don't have any chance to introduce workarounds =(
