### ISSUE TITLE
EA Issue: It is possible to use 'trim($var)' instead (reduces cognitive load)

### ISSUE THREAD

**Issue by MHCreations** [kalessil/phpinspectionsea#1659]
Please delete.

**Comment by orklah** [comment]
Hi,

the notation ` ?? null` means that if what precedes is null, you assign to null. This is litterally a blank operation because the only time where you'll assign to null is when the value was already null to begin with.

Furthermore, as you say, trim() will never return null, so it's unreachable code.

Maybe you meant to use `?:` instead?

**Comment by MHCreations** [comment]
> 
> 
> Hi,
> 
> the notation ` ?? null` means that if what precedes is null, you assign to null. This is litterally a blank operation because the only time where you'll assign to null is when the value was already null to begin with.
> 
> Furthermore, as you say, trim() will never return null, so it's unreachable code.
> 
> Maybe you meant to use `?:` instead?

Yes, I have just now realised my oversight. Using `?:` as intended returns the correct response and avoids EA reduce cognitive load highlights.
 
Thanks.
