### ISSUE TITLE
Php Inspections (EA Extended) | Security | Insecure 'extract(...)' usage (Variable extract Vulnerability)

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1679]
Inspection is ignore default values of properties.

| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) master |
| Language level | PHP 7.2                        |

Example:
~~~
extract(array &$array, int $flags = EXTR_OVERWRITE, string $prefix = "") : int
~~~
error:
~~~php
extract($this->tempData);
~~~
no error:
~~~php
extract($this->tempData, EXTR_OVERWRITE);
~~~

**Comment by ea-inspections-team** [comment]
Thanks for reporting @WinterSilence!

The behaviour is expected: the inspection asks to specify which behaviour is intended (it often requires exploration for flags). If youshare more context on why you are reporting this, we might think of improvements (e.g. message itself).

**Comment by WinterSilence** [comment]
@ea-inspections-team 

> Inspection is ignore default values of properties.

inspection generate error if I'm not pass second optional argument, but work fine if I'm pass default value

**Comment by ea-inspections-team** [comment]
@WinterSilence: correct, that's exactly what the inspections encourages to do. Why placing the default value as argument confuses you?

**Comment by WinterSilence** [comment]
@ea-inspections-team I'm confused by inspection insists that I should pass an argument with default value. Why `extract($this->tempData);` - bad, `extract($this->tempData, EXTR_OVERWRITE)` - good?

**Comment by rentalhost** [comment]
@WinterSilence the possible behaviors of the `extract()` function are broad and somewhat confusing in general. What this inspection suggests is that you specify what you actually want as a result, even if the default argument is the same as expected - indicating that this is what you really want.

In case you are not satisfied with this type of analysis, my suggestion is to just turn it off. But from experience, I can tell you that it already gotten me out of some trouble, and that's why I particularly prefer to repeat the argument to emphasize my expectation of `extract()` behavior (even though in other cases I would really prefer to keep the default argument without repeating it, but this would be an exception).

**Comment by ea-inspections-team** [comment]
Thanks for sharing more details @WinterSilence. We'll drop the inspection from extended-version. Will be kept in ultimate-version.
