### ISSUE TITLE
Make "Except PHPUnit assertions"  option enabled by default

### ISSUE THREAD

**Issue by ivanhoe011** [kalessil/phpinspectionsea#1710]
Per discussion on twitter with @kalessil  (https://twitter.com/kalessil/status/1373929563944804362):

Please make PHP code style inspection for **"Static methods invocation via ->"** disabled for phpunit assertions by default. In phpunit both styles of invocation are correct, as explained in [phpunit docs](https://phpunit.readthedocs.io/en/9.5/assertions.html#static-vs-non-static-usage-of-assertion-methods).

The checkbox **"Except PHPUnit assertions"** should be checked by default.

<img width="692" alt="Screenshot 2021-03-22 at 10 09 54" src="https://user-images.githubusercontent.com/1836505/111971800-062e7900-8afd-11eb-91a8-0161789e1f97.png">

**Comment by ktomk** [comment]
I guess the description in Phpunit docs is merely of historic matters and shifted over into new versions. Per the description there, it is not only that both forms are considered equally right - so there should not be any issue to switch to static calls - it is also the static calls are explained that they were introduced because of code re-use which from best of my knowledge for Phpunit pre-dates PHP 5.4  which introduced traits that provide this kind of code-reuse of the use-case of which the documentation authors write which feels natural for most phpunit users - still thought it has not been considered any issue of all to make it feel that well to switch to traits for that (which is all fine and fair from my perspective).

Therefore I would consider this a vote for static call-ability of the methods and by sheer correctness adhere it it, especially it looks more like an appendix in the long history of Phpunit and I wouldn't let it further grow into other tools.

As both styles are correct as you reason, what prevents to switch to static calls when it's a click away?

Like the inspection says: it remains confusing. even today. why continue the confusion?

**Comment by ea-inspections-team** [comment]
On behalf of @kalessil, the option has been enabled by default.

**Comment by ea-inspections-team** [comment]
@ktomk: reading the linked Twitter thread, the background here is ping from PHPUnit maintainers.

**Comment by ktomk** [comment]
@ea-inspections-team: Well, it requires exact reading ;) But thanks for even more Phpunit support.

**Comment by ea-inspections-team** [comment]
@ktomk, :+1:
