### ISSUE TITLE
Don't suggest random_int as recommendation for mt_rand

### ISSUE THREAD

**Issue by tyteen4a03** [kalessil/phpinspectionsea#1718]
`mt_rand()` is not a cryptographically-safe random number generator method, while `random_int()` is. `random_int()` is [~3.6x slower than `rand()`](https://stackoverflow.com/a/62756282/1049833) because of its nature.

They do different things, therefore `random_int()` should not be considered a replacement for `mt_rand()`.

**Comment by ktomk** [comment]
@tyteen4a03 Which inspection is your report related to? (and further, was there a problem to disable it?)

**Comment by tyteen4a03** [comment]
RandomApiMigrationInspection. 

I can obviously disable it in PHPStorm but the inspection is incorrect to begin with.

**Comment by ktomk** [comment]
No, I didn't want you to ask to disable it at first hand. I had a different inspection in mind for which it would have made sense despite being slower / doing something different.

For "Random API Migration" I don't have that problem (`rand()` goes to `mt_rand()` here) _despite_ I have the inspection option to switch to `random_int()` enabled (and also when disabled):

![image](https://user-images.githubusercontent.com/352517/119154439-751f4400-ba52-11eb-93fd-7bfbdb4bd7cf.png)

Maybe the inspection option is effective on your end? I will run a couple more tests on my end before more conclusions.

**Comment by tyteen4a03** [comment]
Disabling that option does disable the inspection. 

Yes, my concern is the migration inspection is incorrect, as `mt_rand()` and `random_int()` does different things. Additionally `rand()` (and related functions) have been aliases to `mt_rand()` since PHP 7.1 so there's no migration needed.

**Comment by ktomk** [comment]
@tyteen4a03 I first uploaded an uncommented screenshot, maybe reloading does show the annotated one which should highlight the inspection option (not the inspection).

**Comment by tyteen4a03** [comment]
Yes, unchecking that option does make the inspection stop reporting on `mt_rand()`. It should however be not necessary since the suggestion is incorrect (as in, the plugin should never suggest `mt_rand() -> random_int()`).

**Comment by ktomk** [comment]
> Yes, unchecking that option does make the inspection stop reporting on mt_rand(). It should however be not necessary since the suggestion is incorrect (as in, the plugin should never suggest mt_rand() -> random_int(), despite the checkbox existing).

Yes, I'm pretty sure you are the kind of person that is knowledgeable and confident enough to configure the inspections.

This inspection naturally is only for those code-bases where it is _actually_ necessary (which is not on your box as far as I can see). 

So whenever you stumble over the one or other inspection where you wonder, what? why is it even necessary?, it might be a sign you don't need it and you can disable it.

**Comment by tyteen4a03** [comment]
That doesn't mean the inspection is wrong (because it is). 

If this plugin supports < 7.1 then fair game (maybe disable per major version). Otherwise the advice is incorrect for all scenarios. This is what I am saying.

**Comment by ktomk** [comment]
Yes, Phpstorm is (often) used in a PHP language level that is far higher than the origin of the code for which a migration inspection like this one is valuable. E.g. a code base that predates 7 or even 5, often larger, then running named inspections and reviewing the result(s) within a PHP 7.4 language level.

As you might imagine, it is then less a question whether the inspection is correct in a clean theoretic view, but whether it is practically useful in migrating the code-base.

But I can imagine this is an entirely different scenario than the one your report stems from. It's like you wrote, the advice is incorrect for all other scenarios, the inspection is only useful for a very specific migration and otherwise does not make (much) sense.

> maybe disable per major version

Yes, that sounds like good thinking to me. And/or to make use of the checkbox in Phpstorm inspections to not automatically activate new inspections, then they do not have to disable anything and only enable the inspections that are actually correct for their project (projects can differ a lot, therefore it is hard if not impossible to have inspections that always work for everyone).

**Comment by ea-inspections-team** [comment]
Thanks for reporting @tyteen4a03 and for sharing the customization settings @ktomk.

We checked out the Stack overflow link, and if calculated correctly `random_int` is slower for `0,000000893` second.
Weighting out, the delta vs more reliable random numbers, we'd like to keep the behavior unchanged.

We are aware that it's slower, but we don't see real life cases and context where this might hurt anyone.
If you have such examples, it would be great. Thanks!
