### ISSUE TITLE
Hardening json_decode should set default value for associative if not set

### ISSUE THREAD

**Issue by jhard** [kalessil/phpinspectionsea#1732]
Php Inspections (EA Extended) 4.0.6.3
Php 7.3

Current behaviour
--
Having
`$test = json_decode('{}')`
and applying the quick fix for hardening errors handling produces
`$test = json_decode('{}', true, 512, JSON_THROW_ON_ERROR)`
which will break the code because it'll change $test from a stdObject to an array (since associative is null/false by default).

Expected behaviour
--
`$test = json_decode('{}')`
and applying the quick fix for hardening errors handling produces
`$test = json_decode('{}', false, 512, JSON_THROW_ON_ERROR)`

Environment details
---
PhpStorm 2021.1.2
Build #PS-211.7142.44, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-72-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Registry: run.processes.with.pty=TRUE, undo.documentUndoLimit=500, ide.images.show.chessboard=true
Non-Bundled Plugins: A move tab left and right using the keyboard plugin - by momomo.com (12.550), com.jan.evendarker (1.0), com.jetbrains.fast.mouse.scroll (1.5.7), rocks.blackcat.vcl (0.7.2), com.perl5 (2021.1), com.intellij.plugins.html.instantEditing (211.6693.111), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), lv.midiana.misc.phpstorm-plugins.deep-keys (2021.03.26.001), de.espend.idea.php.toolbox (5.1.1), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.209), ru.adelf.idea.dotenv (2021.1)
Current Desktop: KDE

**Comment by niconoe-** [comment]
This is actually configurable in your settings. But I guess you're right that the default configuration should be to decode as object instead of array.

I do not speak Java and I never worked on a pluggin for PHPStorm, but probably switching these could build a default configuration that matches with PHP's default behavior (ARRAY should be false and OBJECT should be true):

https://github.com/kalessil/phpinspectionsea/blob/ad57a4a557daff9fa97df654c467ac5048c2379b/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/apiUsage/JsonEncodingApiUsageInspector.java#L36-L37

What do you think about?

**Comment by ea-inspections-team** [comment]
Thanks for reporting @jhard and @niconoe- for checking the source code.
Agree, we'll change the defaults so they are matching to default behaviour of the function.

**Comment by ea-inspections-team** [comment]
Fixed! The fix will be available in the next release.
