### ISSUE TITLE
Is this project Dead?

### ISSUE THREAD

**Issue by jansor** [kalessil/phpinspectionsea#1823]
Hi 

First i want to thank you for the amazing work put into this project.
We also notice that last release was 5 months ago, i can imagine for  a free project that you moved on to an other challenge.

Can you confirm if this project is dead? Otherwise their are maybe poeple who want to continue this project and you can provide it to the community to maintain it?

Thank you again for all the effort

**Comment by laurinkeithdavis** [comment]
I have the same concerns. I have had some contact with the owner, but it seems like @kalessil has other priorities now. Not knocking that at all, but if that is the case, I hope we can let others step in and take over it. I have a little PS plugin dev, but I'm not a Java programmer. I would still assist as I could.

**Comment by kalessil** [comment]
Hi folks,

The engineers maintaining project are from UA and they have other priorities ATM.
Once thing gets sorted out, it'll be clear how to proceed.

Meanwhile, if there are burning topics, please DM me on Twitter/email - I'll try to get the most critical thing fixed.

Cheers

**Comment by jdreesen** [comment]
@kalessil Probably someone should look into #1805 / #1820 soon, as the release of PhpStorm 2022.1 is around the corner.

**Comment by quadrifolia** [comment]
fix here: https://github.com/kalessil/phpinspectionsea/issues/1805#issuecomment-1105183835

**Comment by aztechowski** [comment]
> Hi folks,
> 
> The engineers maintaining project are from UA and they have other priorities ATM. Once thing gets sorted out, it'll be clear how to proceed.
> 
> Meanwhile, if there are burning topics, please DM me on Twitter/email - I'll try to get the most critical thing fixed.
> 
> Cheers

@kalessil Is there any possibility, that the issue with the crash of the plugin will be fixed soon. I think this issue, beside others, its really , if not burning, then at least annoying.

**Comment by elomonaco** [comment]
> Hi folks,
> 
> The engineers maintaining project are from UA and they have other priorities ATM. Once thing gets sorted out, it'll be clear how to proceed.
> 
> Meanwhile, if there are burning topics, please DM me on Twitter/email - I'll try to get the most critical thing fixed.
> 
> Cheers

While I understand this, there are some of us who paid for this plugin and with that, expect a little more effort since you are getting paid for the product. I'd actually be far more understanding if it was a free plugin as I don't expect it to be their life, but having people pay for it and just say we're too busy to fix things is a bit of a sour response when we ponied up money to ensure the dev doesn't just lose interest and abandons the project or switch to something else because lack of motivation.

I really love this plugin, which is why I've paid for it, but seeing little dumb bugs on a paid plugin and not seeing action is a little upsetting. Issue #1805 for example, the solution is for the user to apply a hacky fix. if nothing else, apply that hacky fix to the paid plugin at least since we're paying good money for something we expect to not be buggy.

To me, either honor those who are paying for the plugin or just make it free and we can all assume things will happen because the author is doing it in their spare time and have a job to do to pay the bills.

I just want the author to make it right to those who are paying for this plugin.

**Comment by nicekiwi** [comment]
> 

Toxic. 

Please take your grievances up with 🇷🇺.

**Comment by gulaandrij** [comment]
Hope you guys are safe. I haven’t canceled my monthly subscription for this plugin and will not cancel it. Hope all russians will die soon and you will be able to continue this amazing work. Слава Україні! 🇺🇦

**Comment by infabo** [comment]
war aside: this project has not seen a commit since the end of 2021. Issues are ignored or at least not commented by a maintainer. Jetbrains subscription can still be bought though. From a professional point of view I don't think this is honest. You could switch to a donation model, while there is no business or technical activity here.

**Comment by elomonaco** [comment]
> war aside: this project has not seen a commit since the end of 2021. Issues are ignored or at least not commented by a maintainer. Jetbrains subscription can still be bought though. From a professional point of view I don't think this is honest. You could switch to a donation model, while there is no business or technical activity here.

I agree, if the dev is _really_ unable to work on it, they should remove the pay wall and make it a donation setup as paying for something means you plans on offering support and not leaving customers stranded (which yes if you paid for it you're a customer).

**Comment by rentalhost** [comment]
Hey guys. In some moments I helped a little in the development of this plugin. There were few moments and few things I could do.

When I noticed that the plugin was stopping to be updated I tried to contact the author. I wanted to be able to continue and make the necessary changes to make it at least functional. However, I didn't get any answers.

I particularly believe that the author is busy with other activities, given their interactions on Github (but which are much smaller than usual too, so maybe there are other reasons).

Because of this, as I also really liked this plugin, I decided to create an alternative. I don't feel good about doing what I'm going to do, but I believe that if I can think of everyone who uses it, I believe it would be a good thing. I created a plugin called **[PHP Hammer](https://plugins.jetbrains.com/plugin/19515-php-hammer)** that has EA inspections. It doesn't have all the inspections, but it has the main ones that exist in this one, and I'm open to suggestions.

I hope @kalessil sees this with good eyes. I'm not trying to take anything from him, but to give you guys an alternative while his plugin is incompatible with new versions of PhpStorm.

**Comment by infabo** [comment]
> but to give you guys an alternative while his plugin is incompatible with new versions of PhpStorm.

I have applied this fix (https://github.com/kalessil/phpinspectionsea/issues/1805#issuecomment-1105183835) back then and the plugin is still compatible in 2022.3. The plugin sometimes throws some exceptions in certain situations, but basically.

What surprises me though: @kalessil is still the repository owner and could easily commit the fix - but he doesn't. If you look at his github contribution activity, he is pretty active. There seems to be some kind of agreement with the "project-team", not to get directly involved in changes/updates or something. I don't know. If he doesn't have anything to do with the project anymore, then he should transfer the repo to another github account.

**Comment by elomonaco** [comment]
I agree, I feel like the reputation of this plugin has taken a major blow because there has been crickets from anyone involved with the project, someone needs to offer us something more official than just "we're busy, thanks for your money". The most glaring issue reported is a simple fix someone on the team could make instead of telling us to do it ourselves.

**Comment by hrst** [comment]
I was also a happy paying user (and still am actually), but at some point I also have to wonder whether this project has a future or not. At least commit the fixes already provided by others ...

**Comment by elomonaco** [comment]
it sounds like there should be some movement wit the project soon according to [this](https://github.com/kalessil/phpinspectionsea/issues/1882) issue.

As a paying customer this makes me happy that something is happening finally.
