### ISSUE TITLE
 Php Inspections (EA Ultimate) add Support for PhpStorm 2022.3.1 

### ISSUE THREAD

**Issue by waleedbasit** [kalessil/phpinspectionsea#1870]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) or Php Inspections (EA Ultimate), which version |
| Language level | e.g. PHP 7.2 (check project settings or composer.json)                        |

Question
--
Just tried installing Php Inspections (EA Ultimate) and it's not compatible with PhpStorm 2022.3.1. 
https://plugins.jetbrains.com/plugin/16935-php-inspections-ea-ultimate-

**Comment by beeyev** [comment]
Double that

**Comment by ghbob** [comment]
@ea-inspections-team @kalessil Any chance of a release that's compatible?
One of the first things I install in PHPStorm :)

For now (2022.3.2) "sideloading" stills works btw, download the jar from here: https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-/versions & install it from disk: https://www.jetbrains.com/help/phpstorm/managing-plugins.html#install_plugin_from_disk

Thanks!

**Comment by rwese** [comment]
If this project is no longer maintained it would be good to know, so we could pick it up as a community project.
I really like it and what it adds to phpstorms inspections, would very much miss it.

**Comment by tlamy** [comment]
I'd say it's pretty dead. No one worked on inspections for basic PHP 8.x features like named parameters, null-safe methods (x?->y()) and such.
Afaik @kalessil handed the project over to some Ukrainian friends due to personal circumstances, and those people obviously have other things in mind for over one year now.

A contributor to PHP Inspections EA, @rentalhost, created [PHP Hammer](https://github.com/hammer-tools/php-hammer) with many new inspections, which (to me) looks really promising.

**Comment by ea-inspections-team** [comment]
Thank you for reporting @waleedbasit , all know crashed are solved in v2023.1 and 2024.1.

@beeyev, @ghbob, @rwese: we are so sorry for the frustration caused by the crashes and lack of support by previous maintainers team. Please contact us on [ea.inspections.team@gmail.com](mailto:ea.inspections.team@gmail.com) (we will arrange one year free license for you).
