### ISSUE TITLE
Maintenance: EA Inspections team, solve compatibility issues and follow contractual obligations

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#1882]
@ea-inspections-team: with all understanding of your situation, please address the compatibility issues ASAP!!!

My requests to get permission/emails/DMs are answered but @ea-inspections-team assured me things under control.
To say I'm frustrated is the least I can do, please sort things out as per your contractual obligations by end of this week!!!

**Comment by dryabov** [comment]
@kalessil Locally I've fixed usage of all deprecated APIs a couple of months ago (just to better understand changes in the Intellij API), and I could share changes (privately or as a public PR):
- minimal supported PhpStorm version is 2021.1
- Java 11 is used for build (instead of 8)
- ErrorReportSubmitter is used instead of Logger's addAppender
- StartupActivity is used instead of ApplicationComponent and ProjectComponent
- some other minor changes to avoid deprecated/removed APIs

**Comment by kalessil** [comment]
Thanks, @dryabov!  Sharing in public, as a diff file(s), or embedded into a comment for this ticket, will work great!

**Comment by kalessil** [comment]
@ea-inspections-team, thanks for getting in touch with an email, but this escalation has to go thru the public channel:
- your actions broke my and the community's trust
- your actions are insulting paying customers, and we likely lost some % of supporters

Please explain what happens and the options to resolve the current situation.
My tone might be overemotional, but I'd like to find  a path forward from this situation which will benefit all parties.

**Comment by dryabov** [comment]
@kalessil https://github.com/dryabov/phpinspectionsea/commit/ec9dba3671195f9cef249d46613bcc95207b668f

**Comment by kaliberx** [comment]
This is amazing, Russian and Ukrainian guys are cooperating to make this working! Thank you @dryabov and @kalessil.

**Comment by elomonaco** [comment]
glad to see this is finally getting some love.

**Comment by ea-inspections-team** [comment]
Hi @kalessil,

Current situation is that since April of last year we don't have people who could work on this project.
I don't want to get into details, but one of the problems is that it was no dispatch/handover.

Not much I can do, only to use the fixes from @dryabov and to release the compatibility fixes on next week.
For other obligations to fix bugs and do new features we need to consult internally.

Sorry that this turned this way, I'm finding out the agreement details only last days.

**Comment by kalessil** [comment]
@ea-inspections-team, thank you for responding here.

To move forward:
- that partially brings light on why no maintenance was happening but not explains missing communications and transparency
- please check the contract for "emergency" cases, get in touch with the contractors today, and handover the credentials they request

Deliverables and expectations:
- Php Inspections (EA Extended), Php Inspections (EA Ultimate) compatibility releases by 30th April
- 100% handover of resources/permissions to the mentioned contractors by 15th May

I'm open to restart

**Comment by dryabov** [comment]
Just in case, I would like to draw your attention to a few points:

1. _[paranoicmode on]_ I've updated Gradle to the latest version, which includes the new gradle-wrapper.jar. IMHO, it would be better to update Gradle manually instead of relying on third-party executables. Alternatively, you can exclude it from the repository, but this may increase the entry threshold for new contributors. _[paranoicmode off]_
2. I've added `org.apache.httpcomponents:fluent-hc` to the dependencies section (it is used by the plugin, but wasn't mentioned there, and so Intellij didn't understand related classes). Note that the final zip package will contain this dependency as well.
3. I've fixed error handling to use the "standard" `errorHandler`, but I haven't tested sending errors to Google Analytics. If possible, please test it.
4. I've added new versions of PhpStorm to .travis.yml, which also needs to be tested to ensure that the versions of Intellij Idea and the PHP plugin match. Probably, 2023.1 should be included there as well (it wasn't released yet when I worked on this patch).

Good luck!

**Comment by kaliberx** [comment]
> * Php Inspections (EA Extended), Php Inspections (EA Ultimate) compatibility releases by 30th April

We are after deadline, still no fix :(

**Comment by ea-inspections-team** [comment]
@kalessil: previous maintainers shared with us the most of credentials (except gmail, perhaps you have original ones somewhere?)

The expectations can not be fulfilled: we received credentials yesterday, but it was no communication about your expectations. We assuming the priorities didn't change and highest is compatibility releases, can you confirm?

**Comment by kalessil** [comment]
@ea-inspections-team, gosh, that turned ugly.

Please ASAP release compatibility fixes - it's an absolute priority. Even if takes 2-3x monthly time - we can revisit the time allocation later, but make it happen,

**Comment by Haehnchen** [comment]
There is now a build for "PhpStorm 2023.1.x": https://github.com/Haehnchen/phpinspectionsea/releases

see PR with changes to get it working based on @dryabov changes https://github.com/kalessil/phpinspectionsea/pull/1883

**Comment by kaliberx** [comment]
@ea-inspections-team When will the new EA Ultimate version be available?

**Comment by ea-inspections-team** [comment]
@kaliberx, given 2-3 business day for approval by JetBrains administrators, it should be available next Tuesday/Wednesday.

**Comment by ea-inspections-team** [comment]
@kalessil, the timeline as you requested:
- today: build and upload extended version of the plugin
- tomorrow: build and upload ultimate version of the plugin

We don't anticipate further delays, and provide post-release monitoring over next week.

**Comment by kalessil** [comment]
Thank you, @ea-inspections-team!

Please ensure to post updates in this thread when uploading new builds and when those get approved, thank you.

**Comment by ea-inspections-team** [comment]
@kalessil: Php Inspections (EA Extended) is uploaded (version 5.0.0.0) and awaits for approval.

Please note following:
- the release includes multiple fixes/improvements which former maintainers worked on
- some tests are failing, but it might be minor compatibility issues

**Comment by kalessil** [comment]
Great! Thank you @dryabov @Haehnchen @ea-inspections-team !

**Comment by ea-inspections-team** [comment]
@kalessil: Php Inspections (EA Ultimate) is uploaded (version 2023.1) and awaits for approval.

Please note:
- we re-uploaded Php Inspections (EA Extended), in order to address issues reported by plugin verification results (JetBrains admins request)

**Comment by ea-inspections-team** [comment]
@kalessil: we addressed points from the last rejection and uploading a new build.

If it doesn't solve the compatibility issues, we are have to increase minimally supported version of IDE.

**Comment by kalessil** [comment]
@ea-inspections-team: thanks for keeping me in the loop.

Please make sure that both plugins have the same supported versions of IDE.

Also, the update page shows you compatibility verification results for each plugin, so you don't have to wait for admins' feedback - if struggling, ask for guidance from them. From my experience, they were always able to help out with pointers.

**Comment by kalessil** [comment]
@ea-inspections-team, can you please update me on your current status?

**Comment by ea-inspections-team** [comment]
@kalessil: yes. 

Thank you for your hints, we were able to build a new release, and QA discovered that settings in Php Inspections (EA Ultimate) are not working. My last update from Wednesday is that the issue is in work.

I'll post a new update on Wednesday when returning  back from a vacation. Probably engineers have everything ready already, and waiting for a confirmation to release.

**Comment by kalessil** [comment]
To keep everyone in the loop: folks get stuck (components I introduced back then), and I'm guiding them as my capacity allows.

**Comment by kaliberx** [comment]
@ea-inspections-team are you still struggling with the Ultimate code? Please share your progress and ETA.

**Comment by kalessil** [comment]
@kaliberx: nope, @ea-inspections-team is unblocked - we are syncing with them tomorrow on the release status.

**Comment by kalessil** [comment]
Hopefully, the last update here: there is "go" for release. I'll also be AFK next week, but verify release availability on Monday.

**Comment by jdreesen** [comment]
I just installed the new EA Ultimate version. Thank you so much! <3
