### ISSUE TITLE
Keep .idea/libraries/php_openapi.xml

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#247]
On commit cb7e2dd80c88e086b264af8b56929ff465e6e52a you have removed this file, and I guess that it is useful on initial setup.

**Comment by kalessil** [comment]
Not sure, we have upgraded dev docs - can we enhance them instead of recovering the file?

**Comment by rentalhost** [comment]
I guess so!

**Comment by kalessil** [comment]
Do you mean that we have great documentation already or something else =) ?

**Comment by rentalhost** [comment]
Definitely true. But I think the information about the openapi configuration should be more detailed. For example, about which files exactly should be added. The current image helps a lot, but I confess I had some difficulty, especially with the recent changes of directory of Jetbrains.

**Comment by davidmpaz** [comment]
Hi @rentalhost, I proposed to ignore the file because after finishing the project set up, I had a broken `php_openapi.xml`, file names that were pointing to fixed paths non existent on my system. 

That's why I added more docs to supply the need of keeping local configurations in git, that later on, could lead to not clean git repository.

I will gladly improve setup instructions alongside with images so it is more clear. I need to say I had same problems too at beginning to realize what needed to be done.

**Comment by rentalhost** [comment]
Same here. Make sense ignore it definitely. But, there not chance to use relative paths? I don't know if it is supported (but still keeps the problem that Jetbrains renames the folder in each version). The unique hope is if it set a relative path on user environment.

**Comment by davidmpaz** [comment]
And then we are depending also to any change they decide to do also with those variables. 

Actually my initial suggestion was to ignore completely the `.idea` directory. This is supposed to be ignored since it is local settings that IDE save, and like you just said, they (JetBrains guys) are changing every time they go to toilet :) for so to speak

I did not suggest to ignore completely first to not be too drastic, i do not know much about other files used in there. But i think the ideal would be to ignore completely, thinking on how many times one configure the project, I think it is more problems to keep files than to remove from git. 

I just updated docs, I will make a PR. Please give me some feedback so I can improve it if you think is needed.

If we came up to the idea that is better to keep the file, I will restore it and do it maybe with some ENV variables, as suggested, to improve portability. But I would not recommend it.

**Comment by kalessil** [comment]
I've merged the PR, already
