### ISSUE TITLE
Change release strategy

### ISSUE THREAD

**Issue by funivan** [kalessil/phpinspectionsea#284]
Current release strategy is following:
Get previous latest version for example 2.3.6 and add +1 to its patch version 
Correct me if i`m wrong.

I suggest to use Semantic Versioning - http://semver.org/

**Why?**
We can deliver patch versions to the users very fast. 
For example: if we have version 2.3.6 all bug fixes will be delivered in 2.3.7. And if users find new bugs, we can fix them and introduce new 2.3.8 version

But new features can be implemented only in 2.4.x
So end-users can works with plugin without bugs (probably without knowing bugs)

Maybe this approach is harder because we should change development process and deliver process.
What do you thing?

**Comment by rentalhost** [comment]
While I think that loveable, it means that we should keep two development branches. Right?
One for stable (_current minor_ with _possible patches_) and another for dev (_minor plus one_).

It will turn harder the development (because you should apply a fix on both branches), BUT I think that currently is the right thing to do.

**Comment by davidmpaz** [comment]
@rentalhost In my opinion all of that could be done in same branch. All changes will contribute to new releases under same major version. I dont see the need to do the work on two development branches.

Still may be needed creating another branch when development will start features for new major version that could brake backward compatibility. To not interfere with stable development, is that what you refer to ?

Thats my five cents. @kalessil is in better conditions to provide feedback :) since he have been making releases/developent since always.

**Comment by rentalhost** [comment]
I am thinking about this situation: let supposes that we are running on version 2.3.0. Then until 2.3.99 we could only works on bugfixes, no new features (according to _semver_). New features come only on 2.4.0.

As this project get new features fastly, let says, one new by week or two, then the minor will increase fast, while the patch will change few. Basically, all bugfixes will happen together to feature (then what we have is the samething that we have currently, but changing _minor_ instead of _patch_).

Another way to think about that is solve all bugfixes before push any new feature. But it maybe limit us to develop new features when we do not like to work on a bugfix on time or it still are be discussed.

**Comment by kalessil** [comment]
@rentalhost got the idea right - we do frequent releases, constantly adding/dropping/moving features. Semantic versioning is not applicable IMO

2nd digit bumped in e.g. following cases:
- we are bumping um minimal platform version requirements;
- we announcing NPEs is not beta anymore;
- or e.g. when I review a group and shifting inspections from it;

**Comment by davidmpaz** [comment]
Point made :+1:

**Comment by funivan** [comment]
@kalessil thanks for the clarification :+1:

**Comment by kalessil** [comment]
@funivan : you are welcome, I think it was a good point to raise the topic - we are on the same page now.

Thank you!
