### ISSUE TITLE
Callables in 'for' loop termination condition - Quick Fix?

### ISSUE THREAD

**Issue by Debeet** [kalessil/phpinspectionsea#309]
Would it be possible to provide a Quick Fix for this scenario?

`for ($i = 0; $i < count($values); $i++)`
=>
`for ($i = 0, $iMax = count($values); $i < $iMax; $i++)`

**Comment by rentalhost** [comment]
There are some problem to I work on it?
(In fact I did not see your assignee, and I'm already working on it.)

**Comment by kalessil** [comment]
Nope, you can grab it =)

**Comment by rentalhost** [comment]
Great! 

Can you explain in which case the [`messageExternal`](https://github.com/kalessil/phpinspectionsea/blob/fb95f2fe4fb713e3fa66233547d7aef1df48f529/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/CallableInLoopTerminationConditionInspector.java#L42) is registered for? I mean, a real code to I test it. I am developing the UTs and QFs, and too the CC (this is the unique line that I can test for because I just not understand what it should be used).

**Comment by kalessil** [comment]
It's used when inspection fires on the incomplete statement (during typing in), this probably can be dropped as inspections are fired only on finished statements.

But it worth double-checking against my code if it's the same case.

**Comment by rentalhost** [comment]
I have done a lot of checks, and I don't found a case where it could be possible, then I dropped it for now. It seems be some [old code](https://github.com/ovr/phpinspectionsea-mirror/blob/master/src/com/kalessil/phpStorm/phpInspectionsEA/inspectors/semanticalAnalysis/CallableInLoopTerminationConditionInspector.java).

**Comment by rentalhost** [comment]
Closing: fixed on #313.

**Comment by Debeet** [comment]
Thank you! 👍
