### ISSUE TITLE
Brainstorm supporter licenses introduction

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#498]
Follow up on https://twitter.com/kalessil/status/901377497123762176

Licensing model:

- Free license
  - The plugin trial (3 months) (needs activation!);
  - IDE Evaluation, IDE OSS licenses and IDE in headless mode (automatically);
- OSS supporter license (given individual, transition model for this year only);
  - A special case for UGs, Patreon (no-go), Indiegogo (done), and PayPal (no-go) supporters;
  - Also covers the project contributors, contributions are welcome;
  - Special case of commercial license;
- Individual license (50$/year, limited support)
- Commercial license (100$/year, priority support; volume licenses)

**Comment by Ayesh** [comment]
Does this mean the ugin will not be open source anymore? If we stop offering installable builds for a free (as in beer), I'm afraid someone will create builds anyway and I believe this leads to fragment the community. 

I simply like this plugin so much that I wouldn't really mind even if I have to buy a license. But I would like to put my honest though that there will be at least an option to request a free of charge license at least for open source contributors and students perhaps, just like how Jetbrains is giving licenses to the same.

I would also like to mention the licensing model of WinRAR. it's a fantastic compression software, that is technically a paid software but with a 40 day free trial. One can use the software after the 40th day, but from what I read, corporates do buy the licenses at that makes the almost all of the revenue. This move made RAR format quite popular in Windows world.

**Comment by kalessil** [comment]
> Free license -> IDE Evaluation and OSS licenses (automatically);
If you run IDE with JetBrains OSS license, plugin runs for free, so OSS community don't have even to apply for a license - we are in sync with IDE licensing. Same for running IDE EAPs and trials - for free, automatically.

**Comment by kalessil** [comment]
> Free license -> The plugin trial (3 months) (needs activation!);

90 days trial period IMO will be enough to make decisions about purchasing the plugin or not.

**Comment by kalessil** [comment]
> Does this mean the plugin will not be open source anymore?

It's 2 parts here:
- If we introduce any kind of licensing, we are loosing JetBrains licenses in our project (as this breaks their OSS definitions);
- Source code availability: the licensing model is extrimely fair to OSS community, so the source code will be available and open for contributions, until signs of piracy (just matter of time when this happens).

@Ayesh: I hope this answers the question, if not please elaborate a little bit more.

**Comment by jaapio** [comment]
I have currently both, a opensource license for my work at phpDocumentor. And a company license for the daily work. How would that work out? I have the payed license since I think good software should be paid.

Will there be a volume license for small teams?

**Comment by kalessil** [comment]
Then we'll issue an OSS licenses for phpDocumentor team, use it for your workspace without limitations :)

For sure: Commercial license targets volume licenses pools, with discounts based on volume size.

**Comment by funivan** [comment]
What is the difference between limited support and priority support?

**Comment by kalessil** [comment]
Tickets by covered by priority support suppose to be handled before tickets by a limited support.

**Comment by kalessil** [comment]
@funivan : I don't see a goal behind maintaining 2 projects (I'll not be able to support OSS version because of time). We have OSS licensing model, the project will be open for contributions - what else is needed (any concerns)?

**Comment by funivan** [comment]
@kalessil no concerns, just wondering. Yep 2 projects is really hard to support.

**Comment by MarlonSchultz** [comment]
I understand the need to make some money in order to have the freedom to further the project.

However, i believe that paying for a non trial version will kill this plugin in the wild. 
Why ?
From my POV its a dev decision to use this tool. Bigger companies seem to rely on codeSniffer, smaller companies rely on single/small-team dev know-how. The single dev itself will very likely not spend money on this (some of them will) and the company will not see the benefits, since phpinspectionsea covers what dev is supposed to know anyways.

So, I somewhat agree with what @funivan said.

My suggestion is quite simple: If you cant afford to spend more time on the project - don´t . I, for example, wanted to contribute, but just haven't found the time. And it´s as simple as that. Keep it fully open source - if the community is huge but the core devs are just a handful - well then so be it. The project must evolve with constraints and not the other way around.  But that´s more of a personal note from my side, since i believe that you´ll end being very frustrated. 

It would be sad if the projects dies because of it, but with this trial/non-trial thing you would just prolong the inevitable.

**Comment by kalessil** [comment]
Thank you @MarlonSchultz : you are precise in your observations (all of them =)).

Submissions of https://goo.gl/forms/f1ZP4BwYV42tnLO02 will show if we should invest into licensing at 
all or just release the project in the wild, pure numbers - so it'll be not much frustration (plain business).

**Comment by cebe** [comment]
@kalessil have you considered setting up something like https://www.patreon.com/ ? You could get monthly payment to work on a fully open source solution.

**Comment by MarlonSchultz** [comment]
@cebe https://www.patreon.com/kalessil

**Comment by kalessil** [comment]
@cebe : yes, I did. The generated revenue there doesn't cover current project needs.

**Comment by kalessil** [comment]
@cebe @MarlonSchultz : it's not a way to go frankly. OSS needs companies support - then it works.

**Comment by cebe** [comment]
I did not know about the patreon site, maybe it needs more marketing to work. I can help make it more popular in Yii Framework Community.

**Comment by funivan** [comment]
@kalessil here is another case:
Paid and free version. 
1. Paid version gets updates as soon as possible.
2. Free version every 6 months (maybe 12 months). 
For example I use free version of plugin. Then bugfixes and new inspections I will get only at specific time (for example at 2018.01.01) 
But I can pay money and get updates every time you release it. Maybe this solution can be usable ;)

**Comment by COil** [comment]
@funivan No really, people will just wait for updates.

**Comment by funivan** [comment]
@COil then okay. But companies that care about code quality can simply invest 100$ and get updates.

**Comment by DarkMukke** [comment]
@funivan problem with that is that people will report issues that are already fixed in the paid version.
I think licensing is okay, paying for a product is fine.

Personally, my company ( 60 IT, 2k+ employees), does pay for licenses, or at least they promised they would. We are still waiting for them to actually do it. 
Jetbrain's licensing allows you to use your personal license commercially as well, as long as it is an individual paying for it.
However I do like Jetbrain's monthly subscriptions for 2 reasons :
- I can't afford a yearly commitment at this time
- I don't know when my company will provide me a commercial license, so i'm having my personal on month to month until they sort it out

So what about a monthly subscription for phpinspectionsea ?
And only a month trial ? That way you still get revenue, but people don't have to commit to the full payment strait away.

**Comment by kalessil** [comment]
@DarkMukke, monthly subscriptions are good for expanding customers base, for our situation (bootstrap commercial product) it'll mean lots of administration efforts. I'm not ready to take it.

Projecting to the given example - the situation is familiar, that's why I mentioned the 3-month trial.

**Comment by kalessil** [comment]
So, I was given an advice I really like (and it doesn't break any heart :)):
- Keep current project free and OSS
- Deviate commercial version (and take risks to fail)

I need to doublethink, but this could work.
