### ISSUE TITLE
Its called writeCData and not writeCdata as it says.

### ISSUE THREAD

**Issue by Jactaen** [kalessil/phpinspectionsea#75]
When writing writeCData it says it should be called writeCdata (new xlmwriter)  - please fix this error

**Comment by kalessil** [comment]
Hi @Jactaen, 

This issue comes from PhpStorm API stabs, where all standard classes documented. This issue specificly is coming from here: https://github.com/JetBrains/phpstorm-stubs/blob/1344ad898f438e7bb00e2d9ee904c46bd900ade8/standard/xmlwriter.php#L278

Php Inspections (EA Extended) takes all my time, so I'd ask for making PR/reporting in the stubs project..

**Comment by Jactaen** [comment]
Thanks for the clarification, ill try if I can find out where to issue it :)

**Comment by dryabov** [comment]
Just FYI: I've made pull request to fix it: https://github.com/JetBrains/phpstorm-stubs/pull/142

**Comment by Jactaen** [comment]
Thanks

**Comment by kalessil** [comment]
Oh, that was fast even for me) Thank you @dryabov
