### ISSUE TITLE
Exception inheritance

### ISSUE THREAD

**Issue by MMauro94** [kalessil/phpinspectionsea#865]
I noticed that for the inspection "Exception handling and annotating" all non-explicitly ignored exceptions are reported. Shouldn't this inspection ignore also all children of ignored exception? So you can add `\RuntimeException` and call it a day, instead of manually adding each exception you want to ignore. Maybe should this be a setting?

For reference, PHPStorm's "Unhandled exception" behaves this way.

**Comment by kalessil** [comment]
Adding a new setting is making sense.

**Comment by sjdaws** [comment]
Not sure if this is related or not but we've noticed on both 2.8.1 and 3.0.1 the `@throws` tag complains if the base exception _isn't_ annotated:
![screen shot 2018-04-17 at 11 43 18 am](https://user-images.githubusercontent.com/659316/38843944-b5ae8d30-4234-11e8-9f89-fc92d0442027.png)

This error comes from Control Flow -> Exceptions handling and annotating

**Comment by sjdaws** [comment]
@kalessil thanks, it seems the whole exception inspection isn't working correctly, this one is thrown by `__call` however will never invoke due to the `method_exists` check prior, this used to be fine as well but now isn't. 

![image](https://user-images.githubusercontent.com/659316/38911726-980ba958-4314-11e8-8ee3-0128db488971.png)

This is happening anywhere an exception is thrown even if it's prevent further up the method for whatever reason we're getting lots of inspection errors that were previously fine.

**Comment by kalessil** [comment]
Both IDE and my plugin has own version of inspection, I'd suggest to leave keep enable only one (you choice ofcourse).

**Comment by sjdaws** [comment]
@kalessil that was the issue for the latter issue thank you, the first error is still happening (which you probably are aware of). Thanks!

**Comment by kalessil** [comment]
In the upcoming release, the inspection has been dropped in favor of a similar one by PhpStorm itself. The bundled one reached needed maturity =)
