### ISSUE TITLE
Transient Dependency Detection false positive with Drupal 8

### ISSUE THREAD

**Issue by jensschulze** [kalessil/phpinspectionsea#901]
Hello,

this is my first post here, so first of all thank you for this great piece of software 👍 !

We have an issue with _Ultimate_: the transient dependency detection identifies any class from the `\Drupal\Components` as transient dependency. But they are actually part of the **Drupal Core** which is required in `composer.json`.
As far as we have checked, any other dependencies to Drupal Core classes are being handled correctly.

Example
======
`ExampleController.php` in our custom module:
```
<?php

namespace Drupal\named_entities\Controller;

use Drupal\Component\Utility\Unicode; // <-- 🔥 Can't get rid of the "This is a transient dependency" mark
use Drupal\Core\Controller\ControllerBase; // <-- OK
use Drupal\Core\Link; // <-- OK
use Drupal\Core\Url; // <-- OK
use Drupal\named_entities\Storage\AssignmentStorageInterface; // <-- OK
use Symfony\Component\DependencyInjection\ContainerInterface; // <-- OK
use Symfony\Component\HttpFoundation\Request; // <-- OK

/**
 * …
```

`composer.json` in our custom module:
```
…
    "require": {
        "php": ">=7.1",
        "drupal/core": "^8.3",
        "symfony/dependency-injection": "^3.2|^4.0",
        "symfony/http-foundation": "^3.2|^4.0",
        "symfony/http-kernel": "^3.2|^4.0"
    }
…
```

The namespaces are declared in `vendor/composer/autoload_psr4.php`:
```
…
    'Drupal\\Core\\' => array($baseDir . '/web/core/lib/Drupal/Core'),
…
    'Drupal\\Component\\' => array($baseDir . '/web/core/lib/Drupal/Component'),
…
```

and the `Unicode` class in question is even explicitly declared in `vendor/composer/autoload_classmap.php` (but as I said before, this issue affects **all** classes in the `\Drupal\Components` namespace):
```
…
    'Drupal\\Component\\Utility\\Unicode' => $baseDir . '/web/core/lib/Drupal/Component/Utility/Unicode.php',
…
```

**Comment by kalessil** [comment]
Hi Jens,

Thank you, happy to hear that you are on Ultimate and liking it =)

This get reported because of this file: https://github.com/drupal/core/blob/8.6.x/lib/Drupal/Component/Utility/composer.json

I'm not sure if this a separate package you can require in the manifest. In some cases it's necessary to ignore such packages in the inspection settings  (the release which bring those settings currently at moderation, once approved you can just ignore this package).

I personally would list the package in the top-level manifest to stay safe from any packaging changes.

**Comment by jensschulze** [comment]
Oops, I missed that one ☠️
Thanks for your help!

**Comment by kalessil** [comment]
Happy to help =)
