### ISSUE TITLE
Test issue template

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#990]
First, thank you for reporting a bug or making a request. That takes time and we appreciate that!

Let's start with common details:
 
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug/False-Positive, Feature request, Support Request     |
| IDE        | IDEA or PhpStorm, which version                          |
| Plugin     | Php Inspections (EA Extended or Ultimate), which version |

Description or screenshot:
--
What can we do for you, dear community member?

Environment details
---
Information from Help -> About dialog might be helpful as well. Skip if you are in doubt.

Notes
---
- Bugs fixed with the highest priority, so features might be postponed. But it shouldn't stop you, right?
- The project support is powered by community funding via [Patreon](https://www.patreon.com/kalessil)

**Comment by rentalhost** [comment]
I did a template for the [HeidiSQL](https://github.com/HeidiSQL/HeidiSQL) project some months ago. **Edit this comment to see hidden things.** Maybe with some adaptations it could works here too.



## Steps to reproduce this issue



1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Current behavior



## Expected behavior



## Possible solution



## Environment



* **PhpStorm version:** 
  
* **This plugin version:**

**Comment by kalessil** [comment]
Oh, I'll update the template after vacation.
